//data brand VETEMENTS

const products =[
    {   
        id: '11',
        category : `accessories`,
        name : `GOTHIC EMBROIDERED HAT`,
        brand : `VETEMENTS`,
        size : [`no size`],
        color : ['black'],
        gender : ['male','female'],
        price : 350,
        productType : `hats`,
        img: ['./project/image/BAG/bag1.png','./project/image/BAG/bag2.png'],
            // t-shirt, pants , suits ,trousers ,...
    },
    {   
        id: '12',
        category : `accessories`,
        name : `LOGO MERINO-WOOL SCARF`,
        brand : `VETEMENTS`,
        size : [`no size`],
        color : ['white','black'],
        gender : ['female'],
        price : 750,
        productType : `scarves`,
        img: ['./project/image/SCARF/scarf1.jpg','./project/image/SCARF/scarf2.jpg'],

    },
    {   
        id: '13',
        category : `apparel`,
        name : `LOGO PRINT RAINCOAT`,
        brand : `VETEMENTS`,
        size : ['S','M','L','XL','XXL'],
        color : ['black'],
        gender : ['male'],
        price : 1350,
        productType : `coast`,
        img: ['./project/image/RAINCOAT/raincoat1.jpg','./project/image/RAINCOAT/raincoat2.png'],
    },
    {   
        id: '14',
        category : `shoes,`,
        name : `SPIKE RUNNER 2 SNEAKERS`,
        brand : `VETEMENTS`,
        size : [7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12],
        color : ['orange','red','blue'],
        gender : ['male','female'],
        price : 590,
        productType : [`shoes`, `sneakers`],
        img: ['./project/image/SNEAKERS/sneakers1.jpg','./project/image/SNEAKERS/sneakers2.jpg'],

    },
    {   
        id: '15',
        category : `shoes`,
        name : `BOOMERANG PATENT LEATHER ANKLE BOOTS`,
        brand : `VETEMENTS`,
        size : [7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12],
        color : ['black',],
        gender : ['female'],
        price : 1390,
        productType : [`shoes`,`boots`],
        img: ['./project/image/BOOTS/boots1.jpg','./project/image/BOOTS/boots2.jpg'],

    },
    {   
        id: '16',
        category : `apparel`,
        name : `REVERSIBLE WHITE & BLACK BOMBER JACKET`,
        brand : `VETEMENTS`,
        size : ['S','M','L','XL','XXL'],
        color : ['black','white'],
        gender : ['women'],
        price : 1590,
        productType : `jackets`,
        img: ['./project/image/JACKETS/jackets1.png','./project/image/JACKETS/jackets2.png'],

    },
    {   
        id: '17',
        category : `apparel`,
        name : `CRYSTAL-EMBELLISHED HOODED SWEATSHIRT IN BLACK`,
        brand : `VETEMENTS`,
        size : ['S','M','L','XL','XXL'],
        color : ['black'],
        gender : ['women'],
        price : 770,
        productType : `hoodie`,
        img: ['./project/image/HOODED/hooded1.jpg','./project/image/HOODED/hooded2.jpg'],

    },
    {   
        id: '18',
        category : `accessories`,
        name : `BLACK LOGO BACKPACK`,
        brand : `VETEMENTS`,
        size : [],
        color : ['black',],
        gender : ['unisex'],
        price : 850,
        productType : `bags`,
        img: ['./project/image/BAG/bag1.png','./project/image/BAG/bag2.png'],

    },
    {   
        id: '19',
        category : `apparel`,
        name : `IT COSTS COTTON T-SHIRT`,
        brand : `VETEMENTS`,
        size : ['S','M','L','XL','XXL'],
        color : ['black'],
        gender : ['unisex'],
        price : 190,
        productType : `t-shirts`,
        img: ['./project/image/T-SHIRT/tshirt1.png','./project/image/T-SHIRT/tshirt2.png'],

    },
    {   
        id: '20',
        category : `accessories`,
        name : `LOGO-ENGRAVED SIGNET RING`,
        brand : `VETEMENTS`,
        size : ['12','13','14','15'],
        color : ['silver'],
        gender : ['unisex'],
        material : ['brass'],
        price : 300,
        productType : `ring`,
        image: ['./project/image/RING/ring1.jpg','./project/image/RING/ring2.jpg'],

    }, 
]
console.log(products);
